# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_styles',
            field=models.CharField(choices=[['BW', 'black and white'], ['PT', 'portrait'], ['FAM', 'family']], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=models.CharField(choices=[['WD', 'Weddings'], ['SCH', 'School Photos'], ['CEL', 'Celebrations']], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
