# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20171127_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
