# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='imager_images.Photo'),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='photo', to='imager_images.Photo'),
        ),
    ]
