# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0007_auto_20171129_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='imager_images.Photo'),
        ),
    ]
